DROP TABLE department CASCADE CONSTRAINTS;

DROP TABLE product CASCADE CONSTRAINTS;

DROP TABLE resolution CASCADE CONSTRAINTS;

DROP TABLE admin CASCADE CONSTRAINTS;

DROP TABLE feedback CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE province CASCADE CONSTRAINTS;

DROP TABLE city CASCADE CONSTRAINTS;

DROP TABLE street CASCADE CONSTRAINTS;

DROP TABLE employee CASCADE CONSTRAINTS;

DROP TABLE issue CASCADE CONSTRAINTS;

DROP TABLE tracking CASCADE CONSTRAINTS;